# Generated by Django 4.2 on 2024-05-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer')], max_length=25, verbose_name='Способ оплаты'),
        ),
    ]
